language: python
python:
  - "3.5"
# command to install dependencies
install:
    - pip install -U pytest
    - pip install -r databases/databases.egg-info/requires.txt
    
# command to run tests
script: 
    - pytest Test.py 
    - py.test --cov=databases --cov-report=term-missing databases/databases/tests.py -q
